apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nbccqvy5j-python 
  janus-idp.io/tekton: nbccqvy5j-python
  backstage.io/kubernetes-id: nbccqvy5j-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nbccqvy5j-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  